name: CI

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: installing node
        uses: actions/setup-node@v5

      - name: Install deps
        run: npm ci

      - name: check Styling
        run: npm run style
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: installing node
        uses: actions/setup-node@v5

      - name: Install deps
        run: npm ci

      - name: linting code
        run: npm run lint 
  build:
    name: Build & Docker
    runs-on: ubuntu-latest
    needs: [lint, style]

    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: installing node
        uses: actions/setup-node@v5

      - name: Install deps
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: 1gazzar1/mooviemood

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
